In [89]:
# You may want to use this example code, for loading in your
# jpg’s and png’s:
import glob
import numpy as np
import matplotlib.pyplot as plt
files = glob.glob("apples/apples/*.jpg")
ColorImgs = []
for myFile in files:
    im = plt.imread(myFile)
    ColorImgs.append(im)
    
ColorImagesArray = np.array(ColorImgs)

for file in files:
    for i in range(3):
        np.ravel(ColorImagesArray)
        
    
    
    
    


array([0., 0., 0.])

In [90]:
ColorImagesArray = np.array(ColorImgs)

In [93]:
ColorImagesArray[2][0,0,:]



array([20, 32, 56], dtype=uint8)

In [94]:
ColorImagesArray[0][:,:,0].shape

(640, 480)

In [77]:
ColorImagsArray[2].shape

(491, 600, 3)

In [69]:
np.array([1,1,1]).reshape(3,1)

array([[1],
       [1],
       [1]])